# Site settings
title: CSE103 Fall 2014
email: yfreund@ucsd.edu

url: "http://cse103.github.io" # the base hostname & protocol for your site

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
